name: Build and Test

on:
  push:
    branches:
      - main

    paths:
      - '.github/workflows/**'
      - 'Cargo**'
      - 'src/**/*.rs'

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-24.04-arm

    env:
      BUILD_TARGET: aarch64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4

      - name: Update and Configure Rust
        run: |
          sudo apt-get install -y musl-tools
          rustup target add ${{ env.BUILD_TARGET }}
          rustup update
          rustup component add clippy

      - name: Dump Toolchain Info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Build
        run: cargo build --target ${{ env.BUILD_TARGET }} --all-features

      - name: Test
        run: cargo test --target ${{ env.BUILD_TARGET }} --all-features

      - name: Lint
        run: cargo clippy --target ${{ env.BUILD_TARGET }} --all-features -- -D warnings
